# fly.toml app configuration file generated for ltl-transformer-portal
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ltl-transformer-portal"
primary_region = "sin" # Singapore (low latency for Sri Lanka & SE Asia)

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
